### ISSUE TITLE
Adding some more defaults

### ISSUE THREAD

**Issue by tjFogarty** [inuitcss/generic.reset#2]
What do you think of including the two of the rules outlined here?
https://github.com/jonathantneal/sanitize.css/issues/2

In practice I've found `* { position: relative; }` to be really useful. Apparently, according to Paul Irish, it's a bit more performant as well.

I've found `* { overflow: hidden; }` to be a bit more troublesome to play with, but I haven't explored it fully yet so I think I just need to reorganise things in my brain first. Again, though, performance benefits.

**Comment by anselmh** [comment]
I don’t think this should be done as a default of a framework. Therefore I’m going to close this for now. Thanks for the proposal though :)

**Comment by tjFogarty** [comment]
No worries, thanks for the feedback!

**Comment by tomasz1986** [comment]
This can cause serious performance issues in Opera (Presto).

See https://github.com/10up/sanitize.css/issues/2#issuecomment-228603408
