### ISSUE TITLE
check your character encoding please... 

### ISSUE THREAD

**Issue by floodedcodeboy** [inuitcss/generic.reset#4]
`Running "compass:dist" (compass) task
    error src/scss/app.scss (Line 11 of bower_components/inuit.css/generic/_reset.scss: Invalid US-ASCII character "\xE2")
Compilation failed in 1 files.
Warning: ↑ Use --force to continue.`

please don't use 'SMART' quotes in your files. it can break things in some environments. 

thanks

**Comment by floodedcodeboy** [comment]
Its happening in a LOT of the files...

**Comment by csshugs** [comment]
@floodedcodeboy 
Did you tried putting `@charset UTF-8` at the top of your main stylesheet?

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
If this issue is still relevant, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

Thanks for pointing this out, though!
